# Generated by Django 4.2.5 on 2023-10-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'marcas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Fabricantes',
        ),
    ]
