# Generated by Django 4.2.5 on 2024-05-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_marcas_delete_fabricantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idfactura', models.AutoField(primary_key=True, serialize=False)),
                ('num_fact', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_fact', models.DateField(blank=True, null=True)),
                ('cod_proveedor', models.IntegerField(blank=True, null=True)),
                ('id_inventario', models.IntegerField(blank=True, null=True)),
                ('anulada', models.SmallIntegerField(blank=True, null=True)),
                ('credito', models.SmallIntegerField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('iddevolucion', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('id_sucursal', models.IntegerField(blank=True, null=True)),
                ('fecha_anulada', models.DateTimeField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('totaldesc', models.FloatField(blank=True, db_column='totalDesc', null=True)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('cod_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nom_proveedor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
    ]
